apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostPID: true
      hostNetwork: true
      hostIPC: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          effect: NoSchedule
        - key: "node-role.kubernetes.io/master"
          effect: NoSchedule
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.9.1
        imagePullPolicy: IfNotPresent
        ports:
          - name: metrics
            containerPort: 9100
            hostPort: 9100
        args:
          - "--path.rootfs=/host"
          - "--path.procfs=/host/proc"
          - "--path.sysfs=/host/sys"
          - "--web.listen-address=:9100"
          - "--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)"
        resources:
        volumeMounts:
          - name: proc
            mountPath: /host/proc
            readOnly: true
          - name: sys
            mountPath: /host/sys
            readOnly: true
          - name: root
            mountPath: /host
            readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
