apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-postgres-pvc
  namespace: sonarqube
spec:
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

