apiVersion: v1
kind: Secret
metadata:
  name: sonar-postgres-secret
  namespace: sonarqube 
type: Opaque
data:
  username: c29uYXJ1c2Vy  # base64 encoded: sonaruser
  password: c29uYXJwYXNz  # base64 encoded: sonarpwd
